### ISSUE TITLE
I need admin permission here please

### ISSUE THREAD

**Issue by llundquist** [IBM-Bluemix-Docs/network-infrastructure#1]

**Comment by llundquist** [comment]
@sheltons are you around now?

**Comment by llundquist** [comment]
I have the files ready to push in my local copy but I can't push, no permissions.

**Comment by sheltons** [comment]
You have an invitation pending. Did it not go through? Lemme send it again.

**Comment by llundquist** [comment]
Got it this time, one from Neal, all done, thanks! I
